wandb_version: 1

MTAT_config:
  desc: null
  value:
    annotations_path: data/MTAT_annotations.csv
    dir_path: /import/research_c4dm/JulienMarcoChrisRMRI/MTAT_wav
    batch_size: 16
    num_workers: 16
    extension: wav
preprocessing_config:
  desc: null
  value:
    sr: 44100
    dataset_sr: 16000
    len_audio_s: 13.6
    len_audio_n: 599760
    len_audio_n_dataset: 217600
    pad_mp3: 8192
    rp: 0.1
    rp_range:
    - 0.9
    - 1.1
train_config:
  desc: null
  value:
    mixed_precision: true
    filters: 16
    dilations:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    dropout_rate: 0.1
    output_dim: 300
    checkpoint_path: checkpoints
    lr: 0.001
    epochs: 1000
    device: cuda
    display_progress_every: 1
    warmup: false
    log_wandb: true
    exp_name: filters_16_do_0.1_od_300
    save_path: checkpoints/filters_16_do_0.1_od_300
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697552845.700954
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
